name: model-training
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py

          # Check if the files are created by listing the directory
          echo "Listing directory contents..."
          ls -l

          # Check if plot.png exists specifically
          if [ -f ./plot.png ]; then
            echo "plot.png found!"
          else
            echo "plot.png not found!"
            exit 1
          fi

          cat metrics.txt >> report.md
          echo "![](./plot.png)" >> report.md
          cml comment create report.md
